// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vacation_Manager.Shared.DB.DataBase;

#nullable disable

namespace Vacation_Manager.Shared.DB.Migrations
{
    [DbContext(typeof(VacationManagerContext))]
    partial class VacationManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.Assistent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("DaysOff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VacationBalance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assistents");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.VacationCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssistentId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssistentId");

                    b.ToTable("VacationCalendars");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.VacationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("VacationCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacationCalendarId");

                    b.ToTable("VacationPeriods");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.VacationCalendar", b =>
                {
                    b.HasOne("Vacation_Manager.Shared.Models.Models.Assistent", "Assistent")
                        .WithMany("VacationCalendars")
                        .HasForeignKey("AssistentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistent");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.VacationPeriod", b =>
                {
                    b.HasOne("Vacation_Manager.Shared.Models.Models.VacationCalendar", "VacationCalendar")
                        .WithMany("VacationList")
                        .HasForeignKey("VacationCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VacationCalendar");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.Assistent", b =>
                {
                    b.Navigation("VacationCalendars");
                });

            modelBuilder.Entity("Vacation_Manager.Shared.Models.Models.VacationCalendar", b =>
                {
                    b.Navigation("VacationList");
                });
#pragma warning restore 612, 618
        }
    }
}
